openapi: 3.0.1
info:
  title: IT Incident Management API
  description: A Salesforce System API for creating and managing high-priority IT support cases (incidents). This API is designed to be used by both traditional applications and AI Assistants.
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Production Server

paths:
  /cases:
    post:
      summary: Create New Incident
      description: Creates a new IT support case. This endpoint is used by an AI assistant to log an issue on behalf of a user.
      operationId: createIncident
      tags:
        - Incident Management
      requestBody:
        description: The details of the new incident to create.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewIncidentRequest'
      responses:
        '201':
          description: Incident Created Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewIncidentResponse'
        '400':
          description: Bad Request - The request body is invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /cases/{caseNumber}:
    get:
      summary: Get Incident Details
      description: Retrieves the full details of a specific IT support case using its unique case number.
      operationId: getIncidentDetails
      tags:
        - Incident Management
      parameters:
        - name: caseNumber
          in: path
          required: true
          description: The unique identifier for the incident (e.g., INC0010012).
          schema:
            type: string
      responses:
        '200':
          description: Successful retrieval of incident details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IncidentDetails'
        '404':
          description: Not Found - No incident with the specified case number exists.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    patch:
      summary: Update Incident Status
      description: Updates the status of an existing case and adds a comment to its history.
      operationId: updateIncident
      tags:
        - Incident Management
      parameters:
        - name: caseNumber
          in: path
          required: true
          description: The unique identifier for the incident (e.g., INC0010012).
          schema:
            type: string
      requestBody:
        description: The new status and a comment explaining the update.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateIncidentRequest'
      responses:
        '200':
          description: Incident Updated Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateIncidentResponse'
        '400':
          description: Bad Request - The request body is invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found - No incident with the specified case number exists.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    NewIncidentRequest:
      type: object
      properties:
        reportedByEmail:
          type: string
          format: email
          example: "user@example.com"
        subject:
          type: string
          example: "Printer Jammed - 3rd Floor"
        description:
          type: string
          example: "The primary multi-function printer is reporting a paper jam."
      required:
        - reportedByEmail
        - subject
        - description

    NewIncidentResponse:
      type: object
      properties:
        caseNumber:
          type: string
          example: "INC0010045"
        status:
          type: string
          example: "New"
        priority:
          type: string
          example: "Medium"
        message:
          type: string
          example: "Case created successfully and routed to the Facilities team."

    UpdateIncidentRequest:
      type: object
      properties:
        newStatus:
          type: string
          enum: [New, In Progress, On Hold, Resolved, Closed]
          example: "In Progress"
        comment:
          type: string
          example: "Initial server reboot performed. Monitoring for stability."
      required:
        - newStatus
        - comment

    UpdateIncidentResponse:
      type: object
      properties:
        caseNumber:
          type: string
          example: "INC0010012"
        updatedStatus:
          type: string
          example: "In Progress"
        message:
          type: string
          example: "Case has been updated successfully."

    IncidentDetails:
      type: object
      properties:
        caseNumber:
          type: string
          example: "INC0010012"
        status:
          type: string
          example: "In Progress"
        priority:
          type: string
          example: "Critical"
        subject:
          type: string
          example: "Email server is slow"
        description:
          type: string
          example: "Users across the EMEA region are reporting significant delays."
        reportedBy:
          type: string
          example: "John Doe"
        assignedTo:
          type: string
          example: "Jane Smith"
        createdDate:
          type: string
          format: date-time
          example: "2025-08-18T08:05:12Z"
        lastModifiedDate:
          type: string
          format: date-time
          example: "2025-08-18T10:22:01Z"
        resolutionNotes:
          type: string
          nullable: true
          example: null

    Error:
      type: object
      properties:
        errorCode:
          type: string
          example: "INVALID_INPUT"
        errorMessage:
          type: string
          example: "The 'newStatus' field is invalid."